val = input("enter some value: ")
print(val, type(val))
val = int(input("enter some value: "))
print(val, type(val))
val = float(input("enter some value: "))
print(val, type(val))
val = bool(input("enter some value: "))
print(val, type(val))
